@file:OptIn(
    org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class,
    org.jetbrains.kotlin.gradle.dsl.abi.ExperimentalAbiValidation::class,
)

import com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask
import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.KotlinMultiplatform
import com.vanniktech.maven.publish.SourcesJar
import groovy.json.JsonSlurper
import io.kotest.framework.gradle.KotestGradleExtension
import java.io.ByteArrayOutputStream
import javax.inject.Inject
import kotlinx.kover.gradle.plugin.dsl.AggregationType
import kotlinx.kover.gradle.plugin.dsl.CoverageUnit
import org.gradle.api.attributes.java.TargetJvmVersion
import org.gradle.api.tasks.testing.AbstractTestTask
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent
import org.gradle.process.ExecOperations
import org.jetbrains.dokka.gradle.engine.parameters.VisibilityModifier
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.TestExecutable
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnPlugin
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnRootExtension
import org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnPlugin
import org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnRootExtension
import org.jetbrains.kotlin.gradle.targets.web.yarn.BaseYarnRootExtension
import org.jetbrains.kotlin.konan.target.HostManager
import org.jetbrains.kotlin.konan.target.KonanTarget
import org.jmailen.gradle.kotlinter.tasks.ConfigurableKtLintTask

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    // The kotest plugin generates the test entry points for the JS, wasm and native targets through KSP.
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotest)
    alias(libs.plugins.ben.manes.versions)
    alias(libs.plugins.detekt)
    alias(libs.plugins.kover)
    alias(libs.plugins.dokka)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.pambrose.envvar)
    alias(libs.plugins.pambrose.kotlinter)
}

// Group and version are defined in gradle.properties. `-PoverrideVersion=...` replaces the version, e.g. for the
// -SNAPSHOT builds published by `make publish-snapshot` and `make publish-local-snapshot`.
providers.gradleProperty("overrideVersion").orNull?.let { version = it }

repositories {
    mavenCentral()
}

// jev4k is embedded in other people's applications, so it targets an older JDK than it builds with: JDK 25 compiles
// it, but the bytecode and the published org.gradle.jvm.version stay at 17, the current mainstream LTS floor.
val jvmTargetVersion = libs.versions.jvm.target.get()
val jvmToolchainVersion = libs.versions.jvm.toolchain.get().toInt()

// Tests run on the build toolchain unless `-PtestJavaVersion=<n>` names another JDK. CI uses it to run the suite
// on the 17 floor and on 21 as well as on 25: `-Xjdk-release=17` limits the API the sources compile against, but
// only running the tests on 17 shows that the bytecode behaves there.
val testJavaVersion = providers.gradleProperty("testJavaVersion").map { it.toInt() }

// The client's User-Agent names the library version. A jar manifest only exists on the JVM, so the version is
// compiled in instead, from a source file generated into commonMain.
abstract class GenerateBuildInfo : DefaultTask() {
    @get:Input
    abstract val version: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val file = outputDir.file("com/pambrose/jev4k/internal/BuildInfo.kt").get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package com.pambrose.jev4k.internal
            |
            |/** The jev4k version, generated by the build. */
            |internal const val JEV4K_VERSION = "${version.get()}"
            |
            """.trimMargin(),
        )
    }
}

val generateBuildInfo =
    tasks.register<GenerateBuildInfo>("generateBuildInfo") {
        version = project.version.toString()
        outputDir = layout.buildDirectory.dir("generated/buildinfo/kotlin")
    }

// IntelliJ runs prepareKotlinIdeaImport on every Gradle sync, so a fresh clone resolves JEV4K_VERSION in the IDE
// without a build first.
tasks.named { it == "prepareKotlinIdeaImport" }.configureEach {
    dependsOn(generateBuildInfo)
}

// The simulator platforms (ios, tvos, watchos) with at least one available device, from the same simctl listing KGP
// reads to pick a device. It is a ValueSource so the configuration cache keeps only this set: the raw listing's sizes
// and timestamps change whenever a simulator runs, which would discard the cache after every simulator test. Only a
// Mac with Xcode has simctl; anywhere else, or if the listing fails, the set is empty.
abstract class SimulatorPlatformsWithDevices : ValueSource<Set<String>, ValueSourceParameters.None> {
    @get:Inject
    abstract val execOperations: ExecOperations

    override fun obtain(): Set<String> {
        if (!HostManager.hostIsMac) return emptySet()
        return runCatching {
            val listing = ByteArrayOutputStream()
            execOperations.exec {
                commandLine("xcrun", "simctl", "list", "devices", "available", "--json")
                standardOutput = listing
            }
            @Suppress("UNCHECKED_CAST")
            val devices = (JsonSlurper().parseText(listing.toString()) as Map<String, Any?>)["devices"]
                as Map<String, List<*>>
            // Runtime ids look like com.apple.CoreSimulator.SimRuntime.tvOS-27-0.
            devices.filterValues { it.isNotEmpty() }.keys
                .map { it.substringAfterLast('.').substringBefore('-').lowercase() }
                .toSortedSet()
        }.getOrDefault(emptySet())
    }
}

val simulatorPlatformsWithDevices: Set<String> = providers.of(SimulatorPlatformsWithDevices::class) {}.get()

kotlin {
    jvmToolchain(jvmToolchainVersion)

    // KGP's ABI validation: `check` runs checkKotlinAbi against the dumps committed under api/, and
    // `make abi-update` (updateKotlinAbi) rewrites them after an intended API change. jev4k.api is the JVM surface,
    // Java callers included; jev4k.klib.api covers the other targets. Regenerate the dumps on macOS, the only host
    // that compiles every target.
    abiValidation()

    jvm {
        compilerOptions {
            jvmTarget = JvmTarget.fromTarget(jvmTargetVersion)
            // jvmTarget alone only sets the class-file version. This also limits the JDK API surface, so building
            // on 25 can't silently link against a method that doesn't exist on 17.
            freeCompilerArgs.add("-Xjdk-release=$jvmTargetVersion")
        }
    }

    // Built and tested for Node.js only: nodejs() shapes jev4k's own test and run tasks. The published artifacts
    // carry no Node-only attribute and would load in a browser, which the docs warn against, since the page would
    // hand the API key to every visitor (TypeSafe's own JS SDK refuses a browser by default).
    js { nodejs() }
    wasmJs { nodejs() }

    macosArm64()
    iosArm64()
    iosX64()
    iosSimulatorArm64()
    tvosArm64()
    tvosSimulatorArm64()
    watchosArm32()
    watchosArm64()
    watchosSimulatorArm64()
    watchosDeviceArm64()
    linuxX64()
    linuxArm64()
    mingwX64()

    compilerOptions {
        // kotlinx.serialization marks parts of its API experimental (the JsonArrayBuilder.addAll overloads, for
        // one). Opting in here keeps @OptIn annotations out of the sources, including the documentation examples,
        // where they would be noise on the page. It does not leak to consumers: opt-in is a compile-time setting
        // for this project only.
        optIn.add("kotlinx.serialization.ExperimentalSerializationApi")
        // BlockingJev is an expect class (a real one on the JVM, an empty one elsewhere); without this flag every
        // compilation warns that expect/actual classes are in Beta.
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateBuildInfo)
            dependencies {
                // api, not implementation: each of these three shows up in the public API, so a consumer compiles
                // against it. HttpClientEngine and JsonElement appear in signatures, and the suspend functions
                // and the inline runBlocking wrappers need the coroutines types.
                api(libs.ktor.client.core)
                api(libs.kotlinx.serialization.json)
                api(libs.kotlinx.coroutines.core)
            }
        }
        // One default engine per platform. CIO can't do HTTPS on Kotlin/Native (Ktor has no native TLS), so the
        // native targets use the engines built on their platform's own HTTP stack. js and wasmJs need nothing:
        // ktor-client-core bundles the fetch-based Js engine there.
        jvmMain.dependencies { implementation(libs.ktor.client.cio) }
        appleMain.dependencies { implementation(libs.ktor.client.darwin) }
        linuxMain.dependencies { implementation(libs.ktor.client.curl) }
        mingwMain.dependencies { implementation(libs.ktor.client.winhttp) }

        commonTest.dependencies {
            implementation(libs.kotest.assertions.core)
            implementation(libs.kotest.framework.engine)
            implementation(libs.ktor.client.mock)
        }
        jvmTest.dependencies {
            implementation(libs.kotest.runner.junit5)
            implementation(libs.mockk)
        }
    }

    // Test binaries this host can build but never run: iosX64's needs an Intel Mac, mingwX64's needs Windows, and a
    // tvOS or watchOS simulator's needs a device for its platform. Xcode installs the iOS simulator by default but not
    // the tvOS or watchOS ones, and KGP runs a simulator test in the first available device; installing a runtime
    // (Xcode → Settings → Components) usually creates devices, and `xcrun simctl create` adds one when it doesn't.
    // Disabling a test task alone still builds its binary under check, so its KSP, compile and link tasks go too. The
    // Linux binaries stay, since `make docker-linux-tests` runs them in containers.
    val unrunnableTestTargets = buildSet {
        if (HostManager.host != KonanTarget.MACOS_X64) add("iosX64")
        if (!HostManager.hostIsMingw) add("mingwX64")
        if ("tvos" !in simulatorPlatformsWithDevices) add("tvosSimulatorArm64")
        if ("watchos" !in simulatorPlatformsWithDevices) add("watchosSimulatorArm64")
    }
    targets.withType<KotlinNativeTarget>()
        .matching { it.name in unrunnableTestTargets }
        .configureEach {
            val target = name.replaceFirstChar(Char::uppercase)
            tasks.named { it == "${name}Test" || it == "kspTestKotlin$target" }.configureEach { enabled = false }
            compilations.named("test") { compileTaskProvider.configure { enabled = false } }
            binaries.withType<TestExecutable>().configureEach { linkTaskProvider.configure { enabled = false } }
        }
}

// The Kotest plugin wires its KSP processor, which generates a native test binary's entry point, only into test
// tasks the host can run. On a Mac the Linux test binaries would link with no specs in them, and linuxArm64 has no
// test task at all. Wiring it in here gives `make docker-linux-tests` real binaries to run in Linux containers. On
// a Linux host the plugin adds the same coordinates, and Gradle keeps one.
dependencies {
    add("kspLinuxX64Test", libs.kotest.framework.symbol.processor)
    add("kspLinuxArm64Test", libs.kotest.framework.symbol.processor)
}

// Java sources (the documentation's JavaInterop example in src/jvmTest/java) compile against the same floor.
// KGP also checks that javac and kotlinc agree on the JVM target. --release, like kotlinc's -Xjdk-release, holds
// javac to the Java 17 API as well as its class-file version, so a newer JDK method can't slip in.
java {
    sourceCompatibility = JavaVersion.toVersion(jvmTargetVersion)
    targetCompatibility = JavaVersion.toVersion(jvmTargetVersion)
}
tasks.withType<JavaCompile>().configureEach { options.release = jvmTargetVersion.toInt() }

// The Kotlin JVM plugin publishes org.gradle.jvm.version from the bytecode target, but the multiplatform plugin
// doesn't. Without it, Gradle can't tell a consumer on an older JDK that jev4k-jvm needs 17.
listOf("jvmApiElements", "jvmRuntimeElements").forEach { name ->
    configurations.named(name) {
        attributes { attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, jvmTargetVersion.toInt()) }
    }
}

// Wire specs into the standard Gradle test tasks rather than a kotest-specific one.
extensions.configure<KotestGradleExtension> {
    customGradleTask.set(false)
}

// Patched versions of vulnerable transitive npm packages in the JS and wasm test toolchains, as in common-utils.
// The toolchains request them with ranges that can't reach the fixed versions on their own. After changing a pin,
// delete build/js/package.json and build/wasm/package.json, then run kotlinUpgradeYarnLock and
// kotlinWasmUpgradeYarnLock: the pins aren't a tracked input, so the upgrade tasks otherwise change nothing.
val yarnResolutions =
    mapOf(
        "ws" to "8.21.0",
        "serialize-javascript" to "7.0.5",
        "diff" to "8.0.3",
        "brace-expansion" to "2.1.4",
        "js-yaml" to "4.3.2",
    )

fun BaseYarnRootExtension.pinResolutions() = yarnResolutions.forEach { (pkg, version) -> resolution(pkg, version) }

plugins.withType<YarnPlugin> { the<YarnRootExtension>().pinResolutions() }
plugins.withType<WasmYarnPlugin> { the<WasmYarnRootExtension>().pinResolutions() }

// The kotest plugin generates spec launchers through KSP, and BuildInfo.kt is generated too; neither follows the
// ktlint style, and only hand-written sources should be linted.
tasks.withType<ConfigurableKtLintTask>().configureEach {
    // A local, so the spec captures a File rather than the build script (which the configuration cache rejects).
    val buildDir = layout.buildDirectory.get().asFile
    exclude { it.file.startsWith(buildDir) }
}

// KDoc site: `make kdocs` writes it to build/dokka/html, and the docs workflow publishes it at /kdocs/.
val repoUrl = "https://github.com/pambrose/jev4k"

dokka {
    moduleName = "jev4k"
    moduleVersion = project.version.toString()
    // Hide members inherited from supertypes (e.g. Throwable's message/cause on every exception);
    // each page links to its supertype instead.
    suppressInheritedMembers = true

    dokkaPublications.html {
        outputDirectory = layout.buildDirectory.dir("dokka/html")
        includes.from("docs/packages.md")
    }

    pluginsConfiguration.html {
        homepageLink = repoUrl
        footerMessage = "jev4k: a Kotlin DSL for TypeSafe's Jev System One model"
    }

    dokkaSourceSets.configureEach {
        // Document only the library: test sources (test classes, fixtures, the examples) are never included.
        if (name.endsWith("Test")) suppress = true

        documentedVisibilities(VisibilityModifier.Public)

        perPackageOption {
            matchingRegex = "com\\.pambrose\\.jev4k\\.internal.*"
            suppress = true
        }

        // "View source" links on every declaration, in whichever source set it lives.
        sourceLink {
            localDirectory = file("src")
            remoteUrl("$repoUrl/tree/master/src")
            remoteLineSuffix = "#L"
        }

        // Link JsonElement, HttpClientEngine, etc. to their libraries' API docs.
        externalDocumentationLinks.register("kotlinx.serialization") {
            url("https://kotlinlang.org/api/kotlinx.serialization/")
        }
        externalDocumentationLinks.register("ktor") {
            url("https://api.ktor.io/")
        }
    }

    // Link JDK types to the docs for the oldest JDK this library supports.
    dokkaSourceSets.named("jvmMain") {
        jdkVersion = jvmTargetVersion.toInt()
    }
}

// Maven Central publishing: the Dokka HTML is packaged as the javadoc jar,
// releases are published automatically, and artifacts are signed only when a GPG key is supplied
// (the Makefile's publish targets pass one via ORG_GRADLE_PROJECT_signingInMemoryKey*).
// com.pambrose.jev4k:jev4k is the multiplatform root module, which Gradle resolves to the right platform artifact;
// Maven consumers depend on com.pambrose.jev4k:jev4k-jvm directly. The Apple artifacts can only be built on macOS, so
// releases are published from a Mac.
mavenPublishing {
    configure(
        KotlinMultiplatform(
            javadocJar = JavadocJar.Dokka("dokkaGeneratePublicationHtml"),
            sourcesJar = SourcesJar.Sources(),
        ),
    )

    pom {
        name = project.name
        description = "A Kotlin DSL and client for TypeSafe's Jev System One model."
        url = repoUrl
        licenses {
            license {
                name = "Apache License 2.0"
                url = "https://www.apache.org/licenses/LICENSE-2.0"
            }
        }
        developers {
            developer {
                id = "pambrose"
                name = "Paul Ambrose"
                email = "paul@pambrose.com"
            }
        }
        scm {
            connection = "scm:git:git://github.com/pambrose/jev4k.git"
            developerConnection = "scm:git:ssh://github.com/pambrose/jev4k.git"
            url = repoUrl
        }
    }

    publishToMavenCentral(automaticRelease = true)
    // Skip signing when no GPG key is provided (e.g., local publishing)
    if (providers.gradleProperty("signingInMemoryKey").isPresent) {
        signAllPublications()
    }
}

detekt {
    buildUponDefaultConfig = true
    allRules = false
    config.setFrom(layout.projectDirectory.file("config/detekt/detekt.yml"))
    baseline = layout.projectDirectory.file("config/detekt/baseline.xml").asFile
    // The plain `detekt` task (the one `check` runs) looks in src/main and src/test by default, which no longer
    // exist. Point it at every source set's Kotlin directory, so it lints what it did before the multiplatform
    // move: all main and test code, without type resolution.
    source.setFrom(
        layout.projectDirectory.dir("src").asFile
            .listFiles()
            .orEmpty()
            .map { it.resolve("kotlin") }
            .filter { it.isDirectory }
            .sorted(),
    )
}

// Code coverage: CI uploads build/reports/kover/report.xml to Codecov. Kover measures the JVM target, which runs
// the common code too.
// Floors that catch a slide, not targets to chase. They sit a few points below what is actually measured, so
// ordinary churn doesn't break the build; raise them once the real numbers have moved up and stayed there.
// `make coverage-log` prints the current figure rather than repeating it here, where it would go stale.
val minLineCoveragePct = 92
val minBranchCoveragePct = 75

kover {
    reports {
        total {
            // Print a coverage summary to the console when koverLog runs.
            log {
                onCheck = true
                format = "<entity> line coverage: <value>%"
                coverageUnits = CoverageUnit.LINE
                aggregationForGroup = AggregationType.COVERED_PERCENTAGE
            }

            verify {
                // Not onCheck: koverVerify can't tell a real regression from "no tests ran", so it would fail every
                // build that skips the tests, such as `build -x jvmTest`. CI runs it explicitly alongside the tests,
                // and `make coverage-verify` runs it locally.
                onCheck = false
                rule("Line coverage floor") {
                    minBound(minLineCoveragePct, CoverageUnit.LINE, AggregationType.COVERED_PERCENTAGE)
                }
                rule("Branch coverage floor") {
                    minBound(minBranchCoveragePct, CoverageUnit.BRANCH, AggregationType.COVERED_PERCENTAGE)
                }
            }
        }
    }
}

tasks.named<Test>("jvmTest") {
    useJUnitPlatform()

    // Run on the JDK named by -PtestJavaVersion, if there is one. Gradle provisions or locates it through the
    // toolchain service, so compilation still happens on jvmToolchainVersion either way.
    if (testJavaVersion.isPresent) {
        javaLauncher =
            javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(testJavaVersion.get())
            }
    }

    // MockK attaches its agent at runtime, and JDK 21+ warns unless dynamic loading is allowed. Only the warning is
    // new in 21: 11 and 17 already accept the option, so every JDK in the test matrix gets it.
    jvmArgs("-XX:+EnableDynamicAgentLoading")
    testLogging {
        events(TestLogEvent.PASSED, TestLogEvent.SKIPPED, TestLogEvent.FAILED)
        exceptionFormat = TestExceptionFormat.FULL
    }
}

// Gradle fails a test task that discovers no tests, so a target whose test binary lost its specs (after a Kotest,
// KSP or Kotlin upgrade, say) can't pass unnoticed. The Kotest plugin switches that guard off for every test task
// once the task graph is ready; this listener, registered after the plugin's, switches it back on. A run filtered
// with --tests is exempt either way.
gradle.taskGraph.whenReady {
    tasks.withType<AbstractTestTask>().configureEach { failOnNoDiscoveredTests.set(true) }
}

tasks.named<Jar>("jvmJar") {
    manifest {
        attributes(
            "Implementation-Version" to project.version,
            // Pin the JPMS module name so it doesn't shift with the jar's file name.
            "Automatic-Module-Name" to "com.pambrose.jev4k",
        )
    }
}

tasks.register<JavaExec>("runExample") {
    group = "application"
    description = "Runs the Triage example against the live API (needs TYPESAFE_API_KEY)"
    val testCompilation = kotlin.jvm().compilations["test"]
    classpath = files(testCompilation.output.allOutputs, testCompilation.runtimeDependencyFiles)
    mainClass = "com.pambrose.jev4k.examples.TriageExampleKt"
}

// A pre-release qualifier is a `.` or `-` delimiter followed by a known unstable
// keyword. `m\d` matches milestones (`-M1`/`.M2`) without catching stable classifiers
// like `-macos`/`-MR1`, and the `[.-]` delimiter catches both dash-style (`-alpha`)
// and dot-style (`.Beta1`) qualifiers while leaving `-jre`/`.Final` stable.
val preReleaseQualifier =
    Regex("""[.-](rc|beta|alpha|m\d|cr|snapshot|eap|dev|milestone|pre)""", RegexOption.IGNORE_CASE)

fun isNonStable(version: String): Boolean = preReleaseQualifier.containsMatchIn(version)

tasks.withType<DependencyUpdatesTask>().configureEach {
    notCompatibleWithConfigurationCache("the dependency updates plugin is not compatible with the configuration cache")
    // Reject a pre-release candidate only when the current version is stable, so
    // dependencies intentionally tracked on a pre-release line still surface updates.
    rejectVersionIf {
        isNonStable(candidate.version) && !isNonStable(currentVersion)
    }
}
